### ISSUE TITLE
Buildpack not using newest version of buildpacks

### ISSUE THREAD

**Issue by uhryniuk** [paketo-buildpacks/eclipse-openj9#240]
Howdy,

Currently I am needing to test out our apps functionality with a newer version of _paketo-buildpacks/liberty_, which at this time just got updated to 2.1.X.

When I run the following command though, it seems that eclipse-openj9 is still using a previous version.
```
pack build --env BP_JAVA_APP_SERVER=liberty \
--env BP_MAVEN_BUILT_ARTIFACT="target/*.[ejw]ar src/main/liberty/config/*" \
--env BP_LIBERTY_PROFILE=jakartaee9 \
--buildpack paketo-buildpacks/eclipse-openj9  \
--buildpack paketo-buildpacks/java \
--docker-host=inherit \
--trust-builder=true \
--creation-time now \
system:.1.0-SNAPSHOT
```

Here are the buildpacks being used when the command is run:
```
===> DETECTING
9 of 25 buildpacks participating
paketo-buildpacks/eclipse-openj9    9.7.0
paketo-buildpacks/ca-certificates     3.3.0
paketo-buildpacks/bellsoft-liberica  9.5.0
paketo-buildpacks/syft                     1.17.0
paketo-buildpacks/maven                6.6.2
paketo-buildpacks/executable-jar    6.3.0
paketo-buildpacks/liberty                1.1.4 <----- expecting to be 2.1.X
paketo-buildpacks/dist-zip              5.3.0
paketo-buildpacks/spring-boot       5.16.0
```

I tried with the newest version that was released today and still getting the same issue. Not sure if this process is automated for updating but wanted to confirm regardless.

Is there also a potentially workaround for the time being?

**Comment by dmikusa-pivotal** [comment]
Friday is release day, so you might have just gotten caught up with an older image while we were in the process of releasing. If you could try again, all of the composite images and builder images should be up-to-date now.

Also, set `--pull-policy=always` to make sure that pack loads the most recent images and not what exists on the Docker daemon already.

If none of that helps, let me know and we can look into it more. Thanks
